### ISSUE TITLE
Album Art Bug

### ISSUE THREAD

**Issue by lnorton89** [Sorrow446/Nugs-DL#7]
I see the line `os.remove("cover.jpg")` but don't see anywhere that is downloading album art or why it would need to be deleted. 

I'm attempting to make some updates to your code and also weren't sure what this does:

`os.chdir("....")` 

Care to shed some light?

**Comment by Sorrow446** [comment]
I forgot to remove that line. I realized halfway through coding that Nugs provide tracks tagged with album covers embedded. 
`os.chdir("....")` Goes back two directories. See the "chdirs" in the albumDirPrep function.

**Comment by lnorton89** [comment]
Gotcha, makes sense.

The `os.chdir("...")` line does not perform that function for me and I do not see anywhere that documents being able to chain two "ups" into one line. I made some changes to your code fixing this on my end as well as implementing album art download and simplifying some of the filenaming as nugs provides their files in a format that is acceptable for me. I've never done a PR so I'm not sure if if its needed/wanted but I'd be happy to share.
